### ISSUE TITLE
Error when running python run.py

### ISSUE THREAD

**Issue by TimeZon3** [s0md3v/roop#104]
Traceback (most recent call last):
  File "D:\MyDownloads\roop-main\run.py", line 25, in <module>
    from core.processor import process_video, process_img
  File "D:\MyDownloads\roop-main\core\processor.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by StanislavAlexandrov** [comment]
Well, it tells you what you need to do. You don't have opencv installed. Try running something like 'pip install opencv-python'

**Comment by kex0** [comment]
https://github.com/s0md3v/roop/wiki/1.-Installation
