### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by TimeZon3** [s0md3v/roop#115]
C:\roop-main>python run.py
Traceback (most recent call last):
  File "D:\MyDownloads\roop-main\run.py", line 25, in <module>
    from core.processor import process_video, process_img
  File "D:\MyDownloads\roop-main\core\processor.py", line 3, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by Toderiox** [comment]
Still have the issue.
