### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by cainiaoiswo** [s0md3v/roop#169]
I got the following error when processing
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\OMNIDREAM\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\developer\roop\roop\run.py", line 264, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "D:\developer\roop\roop\run.py", line 186, in start
    test_face = get_face(cv2.imread(args['source_img']))
  File "D:\developer\roop\roop\core\config.py", line 16, in get_face
    face = get_face_analyser().get(img_data)
  File "C:\Users\OMNIDREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\Users\OMNIDREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by RafaRed** [comment]
same

**Comment by RafaRed** [comment]
Move the face image to the same folder solved.
