### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by Ferallus** [s0md3v/roop#180]
I followed all the instructions. When I try to start, I get 

(venv) C:\deepface\roop>python run.py --gpu
Traceback (most recent call last):
  File "C:\deepface\roop\run.py", line 17, in <module>
    from opennsfw2 import predict_image as dataset
  File "C:\deepface\roop\venv\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "C:\deepface\roop\venv\lib\site-packages\opennsfw2\_inference.py", line 9, in <module>
    import tensorflow as tf  # type: ignore
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\deepface\roop\venv\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\deepface\roop\venv\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

(venv) C:\deepface\roop>

**Comment by Ferallus** [comment]
cuda version 11.6 
CUDNN 8.5.0.96 
python 3.10.9

**Comment by Ferallus** [comment]
problem solved by downgrade protobuf to 3.20.2
`pip uninstall protobuf
pip install protobuf==3.20.2`
