### ISSUE TITLE
AssertionError:face_analysis.py", line 43, in __init__     assert 'detection' in self.models

### ISSUE THREAD

**Issue by paulzhang913** [s0md3v/roop#183]
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\SD\python\python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\softz\roop-main\run.py", line 264, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "D:\softz\roop-main\run.py", line 186, in start
    test_face = get_face(cv2.imread(args['source_img']))
  File "D:\softz\roop-main\core\config.py", line 16, in get_face
    face = get_face_analyser().get(img_data)
  File "D:\softz\roop-main\core\config.py", line 10, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "D:\SD\python\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by henryruhs** [comment]
This usually happens if there is another Python instance is still running and blocking the new thread. I might be wrong, but let us know if killing the process via task manager solved it.

**Comment by xxtyy** [comment]
how did you solve it my friend

**Comment by eggegg2001** [comment]
i cant be solve
