### ISSUE TITLE
The new version not detecting the face

### ISSUE THREAD

**Issue by zaazii** [s0md3v/roop#187]
I use Windows 10 without the --gpu. Yesterday's roop version worked but the latest version is first giving a lot of " Could not load dynamic library" errors and then says to ignore these errors if I don't have a gpu set up. 
Then it says:

Skipping registering GPU devices...
2023-05-31 17:32:01.003297: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-31 17:32:01.171012: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-31 17:32:01.171379: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Pre-trained weights will be downloaded.
Downloading...
From: https://github.com/bhky/opennsfw2/releases/download/v0.1.0/open_nsfw_weights.h5
To: C:\Users\amout\.opennsfw2\weights\open_nsfw_weights.h5
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.2M/24.2M [00:04<00:00, 5.42MB/s]
[WARNING] Unable to determine location of the face in the target. Please make sure the target isn't wearing clothes matching to their skin.
Exception ignored in: <function Pool.__del__ at 0x000001FBAA017640>
Traceback (most recent call last):
  File "C:\Users\amout\anaconda3\lib\multiprocessing\pool.py", line 271, in __del__
  File "C:\Users\amout\anaconda3\lib\multiprocessing\queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

I tried it on several videos that worked with the previous version and I am getting the same errors. 

Edit: I forgot to add that the first time I ran the new version it gave me this error:

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

So I uninstalled protobuf and installed protobuf 3.20.2

**Comment by clrblind** [comment]
same problem

**Comment by GosuDRM** [comment]
Same for me

**Comment by danyderden** [comment]
same

**Comment by clrblind** [comment]
> Comment/delete the rows number 15, 93-95, 200, 201 (basically everything related to opennsfw2) in run.py:

You are make my day!

**Comment by henryruhs** [comment]
sorry we had to do this as there are public demos using this library
