### ISSUE TITLE
(cpu only) onnxruntime dependency missing

### ISSUE THREAD

**Issue by osma** [s0md3v/roop#19]
Hi,

I tried installing under Ubuntu 22.04 / Python 3.10 in a python venv. Installed all the requirements from requirements.txt

When executing `python run.py`, I get this error:

```
Traceback (most recent call last):
  File "/home/xxx/roop/run.py", line 9, in <module>
    from core.processor import process_video, process_img
  File "/home/xxx/roop/core/processor.py", line 2, in <module>
    import insightface
  File "/home/xxx/roop/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime. 
``

I fixed it using `pip install onnxruntime`.

I see from the README that `onnxruntime-gpu` is required for running with a Nvidia GPU. But I don't have a GPU on this machine and it seems `onnxruntime` (without `-gpu`) is still required.

**Comment by s0md3v** [comment]
I have added `onnxruntime` to the requirements.txt.

Thanks!

**Comment by LokeYourC3PH** [comment]
> I have added `onnxruntime` to the requirements.txt.
> 
> Thanks!

Oh lol, just made a pull request XD

**Comment by osma** [comment]
Wow that was quick! Thanks a lot!
Still can't run due to #20.
