### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by XM2510136957** [s0md3v/roop#223]
~~~txt
D:\Work\PythonProjects\roop\venv\Lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
 90%|████████▉ | 526/586 [00:01<00:00, 579.40it/s]Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Tools\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Work\PythonProjects\roop\run.py", line 266, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
                                                                                                                                                   ^^^^^^^
  File "D:\Work\PythonProjects\roop\run.py", line 193, in start
    seconds, probabilities = predict_video_frames(video_path=args['target_path'], frame_interval=100)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\PythonProjects\roop\venv\Lib\site-packages\opennsfw2\_inference.py", line 178, in predict_video_frames
    cv2.destroyAllWindows()  # pylint: disable=no-member
    ^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

100%|██████████| 586/586 [00:20<00:00, 579.40it/s]
~~~

**Comment by henryruhs** [comment]
Don't spam

**Comment by VitaliyAT** [comment]
I have the same problem but with roop installed in 1111
