### ISSUE TITLE
resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))

### ISSUE THREAD

**Issue by hktalent** [s0md3v/roop#233]
macOS cpu:i7
```
$ ls -lah inswapper_128.onnx
-rw-r--r--@ 1 51pwn  staff   529M  6  1 15:28 inswapper_128.onnx

$ python run.py -t t -o t  --max-cores 3
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/roop/run.py", line 227, in <module>
    limit_resources()
  File "/Users/51pwn/MyWork/roop/run.py", line 56, in limit_resources
    resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))
ValueError: current limit exceeds maximum limit
```

<img width="1027" alt="image" src="https://github.com/s0md3v/roop/assets/18223385/9318523b-86a4-4761-bacd-05bae46b6f3f">

**Comment by henryruhs** [comment]
Try with the `--max-memory` flag... Join Discord for help
