### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by xxtyy** [s0md3v/roop#239]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\roop-main\roop-main\run.py", line 266, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
  File "D:\roop-main\roop-main\run.py", line 183, in start
    test_face = get_face(cv2.imread(args['source_img']))
  File "D:\roop-main\roop-main\core\analyser.py", line 16, in get_face
    face = get_face_analyser().get(img_data)
  File "D:\roop-main\roop-main\core\analyser.py", line 10, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "D:\roop-main\roop-main\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by DWFLZXJ** [comment]
Modifying the code below might be able to help you 
#FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.providers)
        FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', root='~/.insightface/models')
