### ISSUE TITLE
module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by Easy47** [s0md3v/roop#255]
I successfully installed all requirements. Nothing went wrong with pip install -r requirements.txt but i have this error when i python run.py
```
Traceback (most recent call last):
  File "C:\Users\33631\Desktop\roop\run.py", line 15, in <module>
    from opennsfw2 import predict_video_frames, predict_image
  File "C:\Users\33631\AppData\Local\Programs\Python\Python39\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "C:\Users\33631\AppData\Local\Programs\Python\Python39\lib\site-packages\opennsfw2\_inference.py", line 15, in <module>
    from ._inspection import make_and_save_nsfw_grad_cam
  File "C:\Users\33631\AppData\Local\Programs\Python\Python39\lib\site-packages\opennsfw2\_inspection.py", line 17, in <module>
    model: tf.keras.Model,
AttributeError: module 'tensorflow' has no attribute 'keras'
```
Thanks

**Comment by henryruhs** [comment]
Still an issues with your platform... Join Discord
