### ISSUE TITLE
NO Module name cv2

### ISSUE THREAD

**Issue by dayaparan** [s0md3v/roop#27]
I get the following error. 

Traceback (most recent call last):
  File "C:\Users\SERVER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.11\roop\run.py", line 9, in <module>
    from core.processor import process_video, process_img
  File "C:\Users\SERVER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.11\roop\core\processor.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by s0md3v** [comment]
google.
