### ISSUE TITLE
Image-Image crushes on Mac. Image-Video crashes in some cases 

### ISSUE THREAD

**Issue by vilgeforc5** [s0md3v/roop#295]
**Describe the bug**
Can't create image-image swap, program just crashes. 
In some cases, program  first time crashes with image-video, but when I retry it runs perfectly fine.

**Details**
MacBook Air Retina, 13-inch, 2019.
Ventura 13.3.1.
Last version of every package.

No. I am not using the `---gpu` flag

**IMAGE- IMAGE:**
2023-06-02 20:13:35.675072: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-02 20:13:35.675072: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2023-06-02 20:14:08.309 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:14:09.934 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:16:24.250 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:16:25.450 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:16:43.396 Python[11682:12477427] +[CATransaction synchronize] called within transaction
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/boris/Library/Python/3.9/lib/python/site-packages/PIL/Image.py", line 3240, in open
    fp.seek(0)
AttributeError: 'str' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/boris/Desktop/roop/run.py", line 141, in select_face
    preview_image(args['source_img'])
  File "/Users/boris/Desktop/roop/run.py", line 109, in preview_image
    img = Image.open(image_path)
  File "/Users/boris/Library/Python/3.9/lib/python/site-packages/PIL/Image.py", line 3242, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
2023-06-02 20:16:47.921 Python[11682:12477427] +[CATransaction synchronize] called within transaction
/Users/boris/Desktop/roop/run.py:110: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
2023-06-02 20:16:52.824 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:17:01.261 Python[11682:12477427] +[CATransaction synchronize] called within transaction
2023-06-02 20:17:07.829 Python[11682:12477427] +[CATransaction synchronize] called within transaction
/Users/boris/Desktop/roop/run.py:128: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
2023-06-02 20:17:21.890 Python[11682:12477427] +[CATransaction synchronize] called within transaction
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/boris/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/boris/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/boris/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/boris/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/boris/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/Users/boris/Library/Python/3.9/lib/python/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

**IMAGE-VIDEO**

2023-06-02 20:21:30.279713: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by vilgeforc5** [comment]
With video in some cases it just hangs with that warning, in some cases it crushes

**Comment by Coutinho159** [comment]
(Im using mac M1 pro)

i have the same issue but with extra error message error about multiprocessing on pool.pv and queues.pv:

It appeared this error message:

(myenv) name@MacBook-Pro-de-Bruno roop % python run.py --max-cores 2    
2023-06-02 18:18:40.580 python[10350:18174948] +[CATransaction synchronize] called within transaction
2023-06-02 18:18:40.639 python[10350:18174948] +[CATransaction synchronize] called within transaction
/Users/name/roop/run.py:110: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
2023-06-02 18:18:43.377 python[10350:18174948] +[CATransaction synchronize] called within transaction
2023-06-02 18:18:43.422 python[10350:18174948] +[CATransaction synchronize] called within transaction
/Users/name/roop/run.py:128: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((180, 180), Image.ANTIALIAS)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/name/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/Users/name/anaconda3/envs/myenv/lib/python3.9/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|████████████████████████████████████████| 883/883 [00:01<00:00, 599.65it/s]
Exception ignored in: <function Pool.__del__ at 0x17c8f85e0>
Traceback (most recent call last):
  File "/Users/name/anaconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
  File "/Users/name/anaconda3/envs/myenv/lib/python3.9/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

**Comment by Coutinho159** [comment]
image-to-image works fine for me and small videos gifs seems to be good., when i try to input bigger videos files it chrashes

**Comment by henryruhs** [comment]
You can either join Discord and get help there or try the latest next branch but not sure if this helps.

@Coutinho159 This is the NSFW filter that kicked in

**Comment by vilgeforc5** [comment]
I solved partly problem by 
1) reloading computer 
2) starting script with sudo
3) placing images/videos in root directory
