### ISSUE TITLE
List out of range error

### ISSUE THREAD

**Issue by kellemar** [s0md3v/roop#3]
I'm getting this issue with a jpg, and an mp4 file.

`Exception in Tkinter callback
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/alvindecruz/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/alvindecruz/Documents/Projects/roop/core/processor.py", line 10, in process_video
    source_face = get_face(cv2.imread(source_img))
  File "/Users/alvindecruz/Documents/Projects/roop/core/config.py", line 9, in get_face
    return sorted(analysed, key=lambda x: x.bbox[0])[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alvindecruz/miniconda3/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/alvindecruz/Documents/Projects/roop/run.py", line 79, in start
    start_processing()
  File "/Users/alvindecruz/Documents/Projects/roop/run.py", line 38, in start_processing
    p.get()
  File "/Users/alvindecruz/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
`

Any idea on what I'm missing?

This is on an M1 Mac running Ventura.

**Comment by s0md3v** [comment]
1. Select the face again in case you misclicked/forgot.
2. Try again with a different face.

If the issue still exists, let me know.

**Comment by LokeYourC3PH** [comment]
I'm facing a similar/same issue:

```
frame= 4777 fps=370 q=-0.0 Lsize=N/A time=00:02:39.23 bitrate=N/A speed=12.3x
video:2557927kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/ubuntu/roop/run.py", line 124, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "/home/ubuntu/roop/run.py", line 89, in start
    start_processing()
  File "/home/ubuntu/roop/run.py", line 30, in start_processing
    process_video(args['source_img'], args["frame_paths"])
  File "/home/ubuntu/roop/core/processor.py", line 10, in process_video
    source_face = get_face(cv2.imread(source_img))
  File "/home/ubuntu/roop/core/config.py", line 9, in get_face
    return sorted(analysed, key=lambda x: x.bbox[0])[0]
IndexError: list index out of range
```

**Comment by s0md3v** [comment]
@LokeYourC3PH @kellemar Can one of you folks give me the images you used? I will be able to figure out whats going on that way.

**Comment by Pawandeep-prog** [comment]
I ran into same problem with my machine Mac m1.
try reinstalling ffmpeg

`brew uninstall --ignore-dependencies ffmpeg`
`brew install ffmpeg`

try it and your problem should be resolved.
