### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by peratik** [s0md3v/roop#319]
**Describe the bug**
After Processing: 100%, GUI closed but console works and not terminated.

```
Processing: 100%|██████████████████████████████████████████████████████████| 77/77 [05:07<00:00,  4.00s/frame, status=.]
Process ForkPoolWorker-8:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**To Reproduce**
1. `python run.py`
2.  Select image and target
3. Click on `Start`

**Details**
What OS are you using?
- [ ] Linux
- [x] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by Moeblack** [comment]
next branch or main branch？

**Comment by peratik** [comment]
main

**Comment by henryruhs** [comment]
Try next and reopen if issue still exists. Thanks

**Comment by peratik** [comment]
> Try next branch and reopen if issue still exists. Thanks

`next` branch:

After Processing: 100%, GUI not closed, console works and not terminated, output is not generated.

![image](https://github.com/s0md3v/roop/assets/6568353/ee8e01c3-729e-40c1-b4d0-269a5e926a73)
