### ISSUE TITLE
AttributeError: 'INSwapper' object has no attribute 'taskname'

### ISSUE THREAD

**Issue by adevinwild** [s0md3v/roop#32]
Hi, 
Just wanted to try this but I'm stuck with this error : 
```bash
Traceback (most recent call last):
  File "/Users/myusername/Documents/GitHub/roop/run.py", line 16, in <module>
    from core.processor import process_video, process_img
  File "/Users/myusername/Documents/GitHub/roop/core/processor.py", line 5, in <module>
    from core.config import get_face
  File "/Users/myusername/Documents/GitHub/roop/core/config.py", line 5, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/insightface/app/face_analysis.py", line 37, in __init__
    elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
         ^^^^^^^^^^^^^^
AttributeError: 'INSwapper' object has no attribute 'taskname'
```

---
## Spec
```
OS : MacOS Ventura  ✅
ffmpeg : Installed ✅
```

## Note
I installed the missing `inswapper_128.onnx` based on this thread : https://github.com/s0md3v/roop/issues/20

**Comment by s0md3v** [comment]
That's weird. What's the version of your `insightface`?

**Comment by adevinwild** [comment]
> That's weird. What's the version of your `insightface`?

How can I check the version installed ?

**Comment by adevinwild** [comment]
Ok : 
```bash
main pip3 show insightface                                                                                                                                                                                                                                                                                                                                          roop
Name: insightface
Version: 0.7.3
```

**Comment by s0md3v** [comment]
I have the same version @adevinwild and it works fine. Moreover, no one has reported this error before you.

I would suggest uninstall it with `pip uninstall insightface`, deleting `.insightface` directory from your home directory if it exists and then reinstalling it.

If that doesn't work, I don't know what to try.
