### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by AniMoster** [s0md3v/roop#357]
How can I resolve this?
I have followed the installation instruction.

```
PS C:\AI\roop> python run.py
Traceback (most recent call last):
  File "C:\AI\roop\run.py", line 3, in <module>
    from roop import core
  File "C:\AI\roop\roop\core.py", line 18, in <module>
    from opennsfw2 import predict_video_frames, predict_image
  File "C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\_inference.py", line 15, in <module>
    from ._inspection import make_and_save_nsfw_grad_cam
  File "C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\_inspection.py", line 17, in <module>
    model: tf.keras.Model,
AttributeError: module 'tensorflow' has no attribute 'keras'
```

**Comment by henryruhs** [comment]
Please join us on Discord as we cannot give individual support to fix platform issues here.

**Comment by AniMoster** [comment]
> Please join us on Discord as we cannot give individual support to fix platform issues here.

Can you please put the link here? I couldn't find it

**Comment by henryruhs** [comment]
It is a pinned issue!

**Comment by westruk** [comment]
> Please join us on Discord as we cannot give individual support to fix platform issues here.

invite link not working
