### ISSUE TITLE
I got error with onnxruntime

### ISSUE THREAD

**Issue by long20014** [s0md3v/roop#413]
**Describe the bug**
```
Exception in thread Thread-8 (process_frames):
Exception in thread Thread-7 (process_frames):
Exception in thread Thread-9 (process_frames):
Exception in thread Thread-4 (process_frames):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-10 (process_frames):
[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=50 ; expr=cublasCreate(&cublas_handle_);

Traceback (most recent call last):

  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
Processing:   1%|▎                                                                  | 1/186 [00:04<13:15,  4.30s/frame]  File "C:\Python310\lib\threading.py", line 953, in run
    self.run()
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "F:\github-codes-2\roop\roop\swapper.py", line 43, in process_frames
  File "F:\github-codes-2\roop\roop\swapper.py", line 43, in process_frames
  File "C:\Python310\lib\threading.py", line 953, in run
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    source_face = get_face_single(cv2.imread(source_img))
    source_face = get_face_single(cv2.imread(source_img))
  File "F:\github-codes-2\roop\roop\swapper.py", line 43, in process_frames
  File "F:\github-codes-2\roop\roop\analyser.py", line 16, in get_face_single
  File "F:\github-codes-2\roop\roop\analyser.py", line 16, in get_face_single
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    source_face = get_face_single(cv2.imread(source_img))
  File "F:\github-codes-2\roop\roop\swapper.py", line 43, in process_frames
  File "F:\github-codes-2\roop\roop\swapper.py", line 43, in process_frames
  File "F:\github-codes-2\roop\roop\analyser.py", line 16, in get_face_single
    face = get_face_analyser().get(img_data)
    face = get_face_analyser().get(img_data)
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    face = get_face_analyser().get(img_data)
    source_face = get_face_single(cv2.imread(source_img))
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
  File "F:\github-codes-2\roop\roop\analyser.py", line 16, in get_face_single
    source_face = get_face_single(cv2.imread(source_img))
    face = get_face_analyser().get(img_data)
  File "F:\github-codes-2\roop\roop\analyser.py", line 16, in get_face_single
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    face = get_face_analyser().get(img_data)
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    model.get(img, face)
    model.get(img, face)
    model.get(img, face)
    model.get(img, face)
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\model_zoo\attribute.py", line 83, in get
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\model_zoo\attribute.py", line 83, in get
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\model_zoo\attribute.py", line 83, in get
    model.get(img, face)
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\model_zoo\landmark.py", line 91, in get
  File "F:\github-codes-2\roop\venv\lib\site-packages\insightface\model_zoo\landmark.py", line 91, in get
    pred = self.session.run(self.output_names, {self.input_name : blob})[0][0]
    pred = self.session.run(self.output_names, {self.input_name : blob})[0][0]
  File "F:\github-codes-2\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
  File "F:\github-codes-2\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    pred = self.session.run(self.output_names, {self.input_name : blob})[0][0]
  File "F:\github-codes-2\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    pred = self.session.run(self.output_names, {self.input_name : blob})[0][0]
    pred = self.session.run(self.output_names, {self.input_name : blob})[0][0]
    return self._sess.run(output_names, input_feed, run_options)
  File "F:\github-codes-2\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
  File "F:\github-codes-2\roop\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=50 ; expr=cublasCreate(&cublas_handle_);


    return self._sess.run(output_names, input_feed, run_options)
    return self._sess.run(output_names, input_feed, run_options)
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'fc1' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=52 ; expr=cudnnCreate(&cudnn_handle_);

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=50 ; expr=cublasCreate(&cublas_handle_);




onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'fc1' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=52 ; expr=cudnnCreate(&cudnn_handle_);


[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_stream_handle.cc ; line=50 ; expr=cublasCreate(&cublas_handle_);


2023-06-10 08:39:15.9783097 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_eb486adf513608dcd45c034ea7ffb8e8>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-MK381CK ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);
```

**To Reproduce**
Run the app with normal step with command
`python run.py --keep-frames --keep-fps --gpu-vendor nvidia`

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**
![image](https://github.com/s0md3v/roop/assets/29418477/ee37e49c-7e4d-44f5-9464-7802f5312c10)

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment]
Please join us on Discord, we cannot provide individual support for platform issues.

**Comment by Erwin11** [comment]
python run.py --execution-provider cuda --execution-threads 3
"--execution-threads 3" change to "--execution-threads 2" or "--execution-threads 1",
 it can use vram 3gb, if use --execution-threads 3, it eat vram about 5.2gb in my tests.
