### ISSUE TITLE
ValueError: Argument must be a dense tensor

### ISSUE THREAD

**Issue by greatjeffzhang** [s0md3v/roop#418]
**Describe the bug**
when I swap face for a video, there is a exception in the next.  When I preview one by one frame, it seems roop work well.
________________________________________________________________
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/jeff/anaconda3/envs/chatglm/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jeff/anaconda3/envs/chatglm/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeff/roop/roop/roop/ui.py", line 304, in <lambda>
    start_button = create_button(window, "Start", lambda: [save_file(save_file_handler, target_path.get()), preview_thread(lambda: start(update_preview))])
  File "/home/jeff/roop/roop/roop/core.py", line 184, in start
    seconds, probabilities = predict_video_frames(video_path=args.target_path, frame_interval=100)
  File "/home/jeff/anaconda3/envs/chatglm/lib/python3.8/site-packages/opennsfw2/_inference.py", line 152, in predict_video_frames
    tf.convert_to_tensor(input_frames),
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1237, in convert_to_tensor_v2
    return internal_convert_to_tensor(
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/constant_op.py", line 226, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/constant_op.py", line 263, in _constant_impl
    tensor_util.make_tensor_proto(
  File "/home/jeff/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/tensor_util.py", line 455, in make_tensor_proto
    raise ValueError("""Argument must be a dense tensor: %s"""
ValueError: Argument must be a dense tensor: [array([[[151., 138., 132.],
        [151., 138., 132.],
        [151., 138., 132.],
        ...,
        [ 69.,  58.,  33.],
        [ 70.,  57.,  33.],
        [ 70.,  57.,  33.]],

       [[151., 138., 132.],
        [151., 138., 132.],
        [151., 138., 132.],
        ...,
        [ 76.,  65.,  40.],
        [ 76.,  65.,  40.],
        [ 77.,  64.,  42.]],

       [[151., 138., 132.],
        [151., 138., 132.],
        [151., 138., 132.],
        ...,
        [ 78.,  67.,  42.],
        [ 78.,  67.,  42.],
        [ 79.,  66.,  44.]],

       ...,

       [[141., 133., 130.],
        [139., 132., 131.],
        [136., 132., 130.],
        ...,
        [ 22.,  15.,  32.],
        [ 22.,  15.,  32.],
        [ 21.,  14.,  31.]],

       [[138., 131., 130.],
        [136., 132., 130.],
        [136., 131., 132.],
        ...,
        [ 19.,  12.,  29.],
        [ 18.,  11.,  28.],
        [ 18.,  11.,  28.]],

       [[136., 132., 130.],
        [136., 131., 132.],
        [135., 130., 131.],
        ...,
        [ 16.,   9.,  26.],
        [ 16.,   9.,  26.],
        [ 15.,   8.,  25.]]], dtype=float32)] - got shape [1, 224, 224, 3], but wanted [1].
  0%|                                          | 1/1241 [00:00<00:25, 48.88it/s]

**To Reproduce**
1. python run.py
2. choose picture and target video
3. see the bug

**Details**
What OS are you using?
- [ yes] Linux  ubuntu20.04
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ yes] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ yes] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
Try Discord for individual platform issues.
