### ISSUE TITLE
Could not find module error

### ISSUE THREAD

**Issue by LORD005** [s0md3v/roop#503]
Hi,
When i try to run the application, i am getting error 

C:\Deepface\roop>python run.py
Traceback (most recent call last):
  File "C:\Deepface\roop\run.py", line 3, in <module>
    from roop import core
  File "C:\Deepface\roop\roop\core.py", line 13, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by henryruhs** [comment]
Platform/Installation issue... closed
