### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by 1ules** [s0md3v/roop#513]
I keep getting the error:

D:\AI\DF\roop>python run.py
Traceback (most recent call last):
  File "D:\AI\DF\roop\run.py", line 3, in <module>
    from roop import core
  File "D:\AI\DF\roop\roop\core.py", line 18, in <module>
    from opennsfw2 import predict_video_frames, predict_image
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2__init__.py", line 4, in <module>
    from ._inference import Aggregation
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2_inference.py", line 15, in <module>
    from ._inspection import make_and_save_nsfw_grad_cam
  File "C:\Users\Jules\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2_inspection.py", line 17, in <module>
    model: tf.keras.Model,
AttributeError: module 'tensorflow' has no attribute 'keras'

I have tried a fresh install and a 1 click install by a youtuber, both are giving me the same error.

**Comment by henryruhs** [comment]
Use Discord
