### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by Bikimaharjan** [s0md3v/roop#543]
Traceback (most recent call last):
  File "E:\Roop\roop\run.py", line 3, in <module>
    from roop import core
  File "E:\Roop\roop\roop\core.py", line 13, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by henryruhs** [comment]
Install the dependencies probably... see instructions
