### ISSUE TITLE
Exception in thread Thread-2:

### ISSUE THREAD

**Issue by PuddingJoker** [s0md3v/roop#566]
my computer is macos m2
when i wanna swap pics report this error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "roop/ui.py", line 304, in <lambda>
  File "roop/core.py", line 180, in start
  File "roop/analyser.py", line 16, in get_face_single
  File "insightface/app/face_analysis.py", line 75, in get
  File "insightface/model_zoo/landmark.py", line 107, in get
  File "insightface/utils/transform.py", line 67, in estimate_affine_matrix_3d23d
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by henryruhs** [comment]
Lower the threads... best way to get platform issues fixed is via Discord - not here.

**Comment by PuddingJoker** [comment]
> Lower the threads... best way to get platform issues fixed is via Discord - not here.

sry, i was discussed on discord, maybe i am in China,the time was different from you, and there are nobody help me, so i have to use github
