### ISSUE TITLE
ImportError: cannot import name 'pywrap_tensorflow' from partially initialized module 'tensorflow.python' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Linus6666** [s0md3v/roop#595]
Did any body met the issue below, how to solve it?
Traceback (most recent call last):
  File "D:\Roop\roop\run.py", line 3, in <module>
    from roop import core
  File "D:\Roop\roop\roop\core.py", line 18, in <module>
    import tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow' from partially initialized module 'tensorflow.python' (most likely due to a circular import) (C:\Users\Administrator\AppData\Local\Programs\Python\Python311\lib\site-packages\tensorflow\python\__init__.py)

**Comment by henryruhs** [comment]
Read the wiki and join Discord for instant help - not on GitHub issues...
