### ISSUE TITLE
Seems like I'm missing the Insightface module

### ISSUE THREAD

**Issue by drorlazar** [s0md3v/roop#6]
after installation I'm getting this error:
```
Traceback (most recent call last):
  File "D:\AI\RoopFaceSwap\roop\run.py", line 8, in <module>
    from core.processor import process_video, process_img
  File "D:\AI\RoopFaceSwap\roop\core\processor.py", line 2, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'
```
what is the best way to fix this? 
thanks

**Comment by s0md3v** [comment]
Read the docs. Google the rest.
