### ISSUE TITLE
inswapper_128.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by nnyy0130** [s0md3v/roop#605]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\hasee/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\hasee/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\hasee/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\hasee/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\hasee/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[ROOP.FACE-SWAPPER] Progressing...
Traceback (most recent call last):
  File "D:\code\roop\run.py", line 6, in <module>
    core.run()
  File "D:\code\roop\roop\core.py", line 235, in run
    start()
  File "D:\code\roop\roop\core.py", line 175, in start
    frame_processor.process_image(roop.globals.source_path, roop.globals.output_path, roop.globals.output_path)
  File "D:\code\roop\roop\processors\frame\face_swapper.py", line 81, in process_image
    result = process_frame(source_face, target_frame)
  File "D:\code\roop\roop\processors\frame\face_swapper.py", line 60, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "D:\code\roop\roop\processors\frame\face_swapper.py", line 48, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "D:\code\roop\roop\processors\frame\face_swapper.py", line 43, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=roop.globals.execution_providers)
  File "D:\code\conda\envs\roop\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "D:\code\conda\envs\roop\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "D:\code\conda\envs\roop\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\code\conda\envs\roop\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\code\conda\envs\roop\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\code\roop\models\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by nnyy0130** [comment]
use the lastest inswapper_128.onnx .

**Comment by huanheaha** [comment]
Have you solved this problem? Where is the latest inswapper_128.onnx downloaded
