### ISSUE TITLE
When choosing the output path for the file, an error occurred.

### ISSUE THREAD

**Issue by xyxsns** [s0md3v/roop#614]
**Describe the bug**
When choosing the output path for the file, an error occurred.

**To Reproduce**
1. Go to 'start'
2. Click on 'save'
3. Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/private/var/www/roop/roop/ui.py", line 304, in <lambda>
    start_button = create_button(window, "Start", lambda: [save_file(save_file_handler, target_path.get()), preview_thread(lambda: start(update_preview))])
  File "/private/var/www/roop/roop/core.py", line 174, in start
    test_face = get_face_single(cv2.imread(args.source_img))
  File "/private/var/www/roop/roop/analyser.py", line 16, in get_face_single
    face = get_face_analyser().get(img_data)
  File "/private/var/www/roop/roop/analyser.py", line 10, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.providers)
  File "/private/var/www/roop/venv/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x] Mac

Are you try to use a GPU?
- [ x] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ x] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
Try to reinstall the dependencies.
