### ISSUE TITLE
roop stop working at 99%. please help.

### ISSUE THREAD

**Issue by NeverBeLazyG** [s0md3v/roop#619]
hey guys, i have a problem. can anyone help me ?
i am trying to face enhance a facewapped video.
i used following commandline: 

`python run.py --execution-provider cuda --frame-processor face_enhancer -t C:\TCHT\1output.mp4 -o C:\TCHT\bbb4.mp4`

the problem is: roop cancels the process at 99% with an error message. the temp folder is full of the enhanced images. but doesent merges it to a video.

following error message:

`find model: C:\Users\youba/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Processing:  99%|███████████████████████████████████████████▌| 389/393 [19:50<00:12,  3.06s/frame, execution_providers=['CUDAExecutionProvider'], threads=8, memory=16]
Traceback (most recent call last):
  File "C:\TCHT\roop\run.py", line 6, in <module>
    core.run()
  File "C:\TCHT\roop\roop\core.py", line 235, in run
    start()
  File "C:\TCHT\roop\roop\core.py", line 192, in start
    frame_processor.process_video(roop.globals.source_path, temp_frame_paths)
  File "C:\TCHT\roop\roop\processors\frame\face_enhancer.py", line 75, in process_video
    roop.processors.frame.core.process_video(None, temp_frame_paths, process_frames)
  File "C:\TCHT\roop\roop\processors\frame\core.py", line 56, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, progress)
  File "C:\TCHT\roop\roop\processors\frame\core.py", line 48, in multi_process_frame
    future.result()
  File "C:\Users\youba\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\youba\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\youba\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\TCHT\roop\roop\processors\frame\face_enhancer.py", line 62, in process_frames
    result = process_frame(None, temp_frame)
  File "C:\TCHT\roop\roop\processors\frame\face_enhancer.py", line 53, in process_frame
    target_face = get_one_face(temp_frame)
  File "C:\TCHT\roop\roop\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Users\youba\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\Users\youba\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\retinaface.py", line 208, in detect
    assert input_size is not None or self.input_size is not None
AssertionError`

this is the error message
can anyone help please ?

thank you

**Comment by duanxiaoyun2003** [comment]
I had a similar situation
 return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedConv node. Name:'conv_9_conv2d' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 134217728

**Comment by henryruhs** [comment]
I think your execution-threads are to high and you ran out of RAM or VRAM.

**Comment by NeverBeLazyG** [comment]
i took another target image and it worked after that change. but still thanks for hints. btw. i found out, that it doesent matter which target or source image you put into the argument. the enhance pipeline doesent seem to use it. so roop should fix this. because it gives error if no -t argument is given. but its not used.
