### ISSUE TITLE
roop cannot use the GPU to change faces, and an error is reported halfway.

### ISSUE THREAD

**Issue by sonicno1** [s0md3v/roop#635]
2023-06-27 16:54:17.6660699 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_eb486adf513608dcd45c034ea7ffb8e8>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=aaaaa; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=aaaaa ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

Processing:  52%|▌| 144/275 [02:25<04:15,  1.95s/frame, execution_providers=['CUDAExecutionProvider'], threads=8, memor2023-06-27 16:54:18.0711671 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_eb486adf513608dcd45c034ea7ffb8e8>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=aaaaa ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=aaaaa  ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=164 ; expr=cublasCreate(&cublas_handle_);

Processing:  53%|▌| 145/275 [02:26<02:10,  1.01s/frame, execution_providers=['CUDAExecutionProvider'], threads=8, memor
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\Software\Ai-Soft\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\Software\Ai-Soft\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "D:\Software\Ai-Soft\roop\roop\core.py", line 192, in start
    frame_processor.process_video(roop.globals.source_path, temp_frame_paths)
  File "D:\Software\Ai-Soft\roop\roop\processors\frame\face_swapper.py", line 86, in process_video
    roop.processors.frame.core.process_video(source_path, temp_frame_paths, process_frames)
  File "D:\Software\Ai-Soft\roop\roop\processors\frame\core.py", line 56, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, progress)
  File "D:\Software\Ai-Soft\roop\roop\processors\frame\core.py", line 48, in multi_process_frame
    future.result()
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Software\Ai-Soft\roop\roop\processors\frame\face_swapper.py", line 65, in process_frames
    source_face = get_one_face(cv2.imread(source_path))
  File "D:\Software\Ai-Soft\roop\roop\face_analyser.py", line 20, in get_one_face
    face = get_face_analyser().get(frame)
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\site-packages\insightface\app\face_analysis.py", line 75, in get
    model.get(img, face)
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 67, in get
    face.embedding = self.get_feat(aimg).flatten()
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 84, in get_feat
    net_out = self.session.run(self.output_names, {self.input_name: blob})[0]
  File "D:\Software\Ai-Soft\roop\Python3.10\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_128' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::Cud

**Comment by henryruhs** [comment]
Lower threads...
