### ISSUE TITLE
When I try to run the program, the following error occurs

### ISSUE THREAD

**Issue by sun-i** [s0md3v/roop#64]
C:\Users\can\Desktop\deepFace\roop\venv\Scripts\python.exe C:/Users/can/Desktop/deepFace/roop/run.py
Traceback (most recent call last):
  File "C:\Users\can\Desktop\deepFace\roop\run.py", line 22, in <module>
    from core.processor import process_video, process_img
  File "C:\Users\can\Desktop\deepFace\roop\core\processor.py", line 5, in <module>
    from core.config import get_face
  File "C:\Users\can\Desktop\deepFace\roop\core\config.py", line 4, in <module>
    face_analyser = insightface.app.FaceAnalysis(name='buffalo_l', providers=core.globals.providers)
  File "C:\Users\can\Desktop\deepFace\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by henryruhs** [comment]
I assume the path `~/.insightface/models/` and therefore models cannot be resolved. Is it present somewhere?

**Comment by henryruhs** [comment]
Join Discord for installation help.

**Comment by xxtyy** [comment]
how did you solve it
