### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras', but they are installed correctly

### ISSUE THREAD

**Issue by angelluce25** [s0md3v/roop#640]
I have tensorflow and keras installed with both versions 2.12.0.
but still when trying to execute it warns me of the error

when executing run.py
Traceback (most recent call last):
   File "D:\IDM downloads\for ia video\roop\roop\core.py", line 22, in <module>
     import roop.ui as ui
   File "D:\IDM downloads\for ia video\roop\roop\ui.py", line 12, in <module>
     from roop.predicter import predict_frame
   File "D:\IDM downloads\for ia video\roop\roop\predicter.py", line 2, in <module>
     import opennsfw2
   File "C:\Users\gonza\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
     from ._inference import Aggregation
   File "C:\Users\gonza\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\_inference.py", line 15, in <module>
     from ._inspection import make_and_save_nsfw_grad_cam
   File "C:\Users\gonza\AppData\Local\Programs\Python\Python310\lib\site-packages\opennsfw2\_inspection.py", line 17, in <module>
     model: tf.keras.Model,
AttributeError: module 'tensorflow' has no attribute 'keras'

- [ ] Windows 
- [ ] NVIDIA 1050ti

![Screenshot_1](https://github.com/s0md3v/roop/assets/121592021/d43d2caa-d3f5-4f55-874e-818ccce10be7)

**Comment by henryruhs** [comment]
https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#module-xxx-has-no-attribute-xxx
