### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10054]

### ISSUE THREAD

**Issue by lanzhi50253** [s0md3v/roop#654]
**Describe the bug**
urllib.error.URLError: <urlopen error [WinError 10054]

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [* ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ *] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ *] I have the latest code from the github repository
- [* ] I have followed the installation guide

(roop) C:\@noinstall\roop>python run.py
Traceback (most recent call last):
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\@noinstall\roop\run.py", line 6, in <module>
    core.run()
  File "C:\@noinstall\roop\roop\core.py", line 208, in run
    if not frame_processor.pre_check():
  File "C:\@noinstall\roop\roop\processors\frame\face_swapper.py", line 30, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "C:\@noinstall\roop\roop\utilities.py", line 134, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\nistly_lan\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by henryruhs** [comment]
It cannot download the `inswapper_128.onnx` and copy it to the `models` directory. Not sure why... therefore I suggest you do it manually:

Download: https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx
