### ISSUE TITLE
OSError WinError 123

### ISSUE THREAD

**Issue by ELN23** [s0md3v/roop#665]
I get this error message when starting the CPU-only Launcher:

Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

-----------------------------------------
TroubleChute Roop CPU-Only One-Line Launcher
https://tc.ht/ & YouTube.com/TroubleChute
-----------------------------------------
Launching Roop CPU-Only...
download_path: C:\Program Files\AI\stable-diffusion-webui♂env\Lib\site-packages\insightface\models\buffalo_l
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Program Files\AI\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "C:\Program Files\AI\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "C:\Program Files\AI\roop\roop\core.py", line 141, in start
    if not frame_processor.pre_start():
  File "C:\Program Files\AI\roop\roop\processors\frame\face_swapper.py", line 38, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
  File "C:\Program Files\AI\roop\roop\face_analyser.py", line 23, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\Program Files\AI\roop\roop\face_analyser.py", line 17, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.execution_providers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\download.py", line 68, in download_file
    os.makedirs(dirname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Program Files\\AI\\stable-diffusion-webui\x0benv'

### I think I know I have to change the "x0B" to "\v" but I just don't now in which file. Where can I find that file?" ###

**Comment by henryruhs** [comment]
Wrong repository...

**Comment by ELN23** [comment]
Sorry, I' m a layman at this.. what do you mean by that and how can I fix the error exactly?
