### ISSUE TITLE
Could you please tell me the reason for the following error message?

### ISSUE THREAD

**Issue by cavan-fly** [s0md3v/roop#694]
Could you please tell me the reason for the following error message?
The UI has started normally, but when I click the start button, I encounter this problem.

system： win10 (21h2)
python：3.10.9
CUDA/CuDNN  installed.
Microsoft C++ Tools  installed.
====================================================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python3109\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\roop\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "C:\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "C:\roop\roop\core.py", line 141, in start
    if not frame_processor.pre_start():
  File "C:\roop\roop\processors\frame\face_swapper.py", line 38, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
  File "C:\roop\roop\face_analyser.py", line 23, in get_one_face
    face = get_face_analyser().get(frame)
  File "C:\roop\roop\face_analyser.py", line 17, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.execution_providers)
  File "C:\roop\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by henryruhs** [comment]
Something is off with the source image... try another one

**Comment by cavan-fly** [comment]
not the source image maybe, i have try many images. would you please think the other reason for me ? thanks very much.

**Comment by cavan-fly** [comment]
I finally found the reason.
My country cannot access github without a VPN. . . .
I didn't set vpn to global mode before, so buffalo_l has not been downloaded.
It only downloads in dos mode when it is run for the first time.
hope these words can help more people.
