### ISSUE TITLE
i get an error when i try to enhance faces on a rooped-video

### ISSUE THREAD

**Issue by NeverBeLazyG** [s0md3v/roop#701]
Hello guys,

i get an error when i try to enhance faces on a rooped-video. can you help me please what is the problem here ?

```
PS C:\tools\roop> python run.py --execution-provider cuda --frame-processor face_enhancer -t C:\Users\youba\Desktop\202307-09-2.mp4 -o C:\Users\youba\Desktop\out.mp4
100%|████████████████████████████████████████████████████████████████████████████▉| 4454/4458 [00:10<00:00, 544.65it/s]Traceback (most recent call last):
  File "C:\tools\roop\run.py", line 6, in <module>
    core.run()
  File "C:\tools\roop\roop\core.py", line 212, in run
    start()
  File "C:\tools\roop\roop\core.py", line 159, in start
    if predict_video(roop.globals.target_path):
  File "C:\tools\roop\roop\predicter.py", line 24, in predict_video
    _, probabilities = opennsfw2.predict_video_frames(video_path=target_path, frame_interval=100)
  File "C:\Users\youba\miniconda3\lib\site-packages\opennsfw2\_inference.py", line 178, in predict_video_frames
    cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

100%|█████████████████████████████████████████████████████████████████████████████| 4458/4458 [00:10<00:00, 427.68it/s]
```

**Comment by NeverBeLazyG** [comment]
solved: needed to reinstall opencv

**Comment by henryruhs** [comment]
like written in the wiki...
