### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by 631068264** [s0md3v/roop#714]
**Describe the bug**

```
CUDA_VISIBLE_DEVICES=3 python run.py --execution-provider cuda
/data/home/yaokj5/dl/apps/roop/roop/models
Traceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/roop/roop/run.py", line 6, in <module>
    core.run()
  File "/data/home/yaokj5/dl/apps/roop/roop/roop/core.py", line 214, in run
    window = ui.init(start, destroy)
  File "/data/home/yaokj5/dl/apps/roop/roop/roop/ui.py", line 38, in init
    ROOT = create_root(start, destroy)
  File "/data/home/yaokj5/dl/apps/roop/roop/roop/ui.py", line 51, in create_root
    root = ctk.CTk()
  File "/data/home/yaokj5/anaconda3/envs/roop/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 38, in __init__
    tkinter.Tk.__init__(self, **pop_from_dict_by_set(kwargs, self._valid_tk_constructor_arguments))
  File "/data/home/yaokj5/anaconda3/envs/roop/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux

Are you try to use a GPU?

- [ ] NVIDIA

**Screenshots**

**Sanity Check**
- [ ] I have the latest code from the github repository
- [ ] I have followed the installation guide

**Comment by henryruhs** [comment]
If you play with the ENV you should know what you are doing...
