### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by tonkoponko** [s0md3v/roop#725]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\darkh/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\darkh/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\darkh/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\darkh/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\darkh/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\roop\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\darkh\AppData\Roaming\Python\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "D:\AI_repo\roop\roop\ui.py", line 91, in <lambda>
    preview_button = ctk.CTkButton(root, text='Preview', cursor='hand2', command=lambda: toggle_preview())
  File "D:\AI_repo\roop\roop\ui.py", line 204, in toggle_preview
    update_preview()
  File "D:\AI_repo\roop\roop\ui.py", line 224, in update_preview
    temp_frame = frame_processor.process_frame(
  File "D:\AI_repo\roop\roop\processors\frame\face_swapper.py", line 66, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "D:\AI_repo\roop\roop\processors\frame\face_swapper.py", line 54, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "C:\tools\miniconda3\envs\roop\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'

What should I do ? It's worked before but now giving eror even after clean install

**Comment by henryruhs** [comment]
You are using the next branch and it seems to be outdated as well. Updating via git pull should help, otherwise join us on Discord for a chat.
