### ISSUE TITLE
Just git cloned the regular today (not 'next') - getting AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by MantisTree** [s0md3v/roop#727]
As title says, ran **git clone https://github.com/s0md3v/roop** around noon today. Now getting the error below. preview only invokes this error on some frames, others work fine.

Also (may be unrelated) getting frequent "libpng error: Write Error" - disk has several GB free. Each time, program continues and successfully writes the next frames.

**python run.py -v** reveals version "roop 1.1.0"

=================

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "d:\roop\roop\ui.py", line 85, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "d:\roop\roop\ui.py", line 175, in select_output_path
    start()
  File "d:\roop\roop\core.py", line 168, in start
    frame_processor.process_video(roop.globals.source_path, temp_frame_paths)
  File "d:\roop\roop\processors\frame\face_swapper.py", line 88, in process_video
    roop.processors.frame.core.process_video(source_path, temp_frame_paths, process_frames)
  File "d:\roop\roop\processors\frame\core.py", line 76, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, lambda: update_progress(progress))
  File "d:\roop\roop\processors\frame\core.py", line 54, in multi_process_frame
    future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\roop\roop\processors\frame\face_swapper.py", line 74, in process_frames
    result = process_frame(source_face, temp_frame)
  File "d:\roop\roop\processors\frame\face_swapper.py", line 59, in process_frame
    many_faces = get_many_faces(temp_frame)
  File "d:\roop\roop\face_analyser.py", line 32, in get_many_faces
    return get_face_analyser().get(frame)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by henryruhs** [comment]
The face analyser opened an image that is either empty or corrupt as it has no dimensions.

Reach out via Discord for a chat, I like to fix that issue for others.
