### ISSUE TITLE
[ROOP.CORE] ffmpeg is not installed.

### ISSUE THREAD

**Issue by orgsiedur** [s0md3v/roop#729]
[ROOP.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "E:\gitSource\roop\run.py", line 6, in <module>
    core.run()
  File "E:\gitSource\roop\roop\core.py", line 205, in run
    if not pre_check():
           ^^^^^^^^^^^
  File "E:\gitSource\roop\roop\core.py", line 128, in pre_check
    update_status('ffmpeg is not installed.')
  File "E:\gitSource\roop\roop\core.py", line 136, in update_status
    ui.update_status(message)
  File "E:\gitSource\roop\roop\ui.py", line 124, in update_status
    status_label.configure(text=text)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'
![image](https://github.com/s0md3v/roop/assets/139244302/94da0361-9636-4b98-a029-af63e3685160)

**Comment by henryruhs** [comment]
Read the wiki/Installation guide and join Discord for help.
