### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Shoichii** [s0md3v/roop#742]
## Description

after start I get error

## Error

Traceback (most recent call last):
  File "C:\Users\khayn\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\deepfake\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\deepfake\roop\ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\deepfake\roop\ui.py", line 199, in select_output_path
    start()
  File "D:\deepfake\roop\core.py", line 133, in start
    if not frame_processor.pre_start():
  File "D:\deepfake\roop\processors\frame\face_swapper.py", line 45, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
  File "D:\deepfake\roop\face_analyser.py", line 30, in get_one_face
    many_faces = get_many_faces(frame)
  File "D:\deepfake\roop\face_analyser.py", line 41, in get_many_faces
    return get_face_analyser().get(frame)
  File "D:\deepfake\venv\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "D:\deepfake\venv\lib\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

## Details

What operating system are you using?

- [*] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [*] CPU
- [ ] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [*] 1.2.0
- [ ] next

**Comment by henryruhs** [comment]
It tries to figure out the dimension of a image that is None... try another one please

**Comment by Shoichii** [comment]
> It tries to figure out the dimension of a image that is empty (None)... try another one please


I tried different ones. Does not help

**Comment by henryruhs** [comment]
Nothing I can do from my side... sorry
