### ISSUE TITLE
[Bug] Enhancer stops in Process

### ISSUE THREAD

**Issue by threeforces** [s0md3v/roop#744]
## Description

Currently, the Face Enhancher always stops in the middle of the process. It always stops when processing a certain frame. In my example, always at frame 383.

Is there a way to eliminate this error?

## Error

Paste the error or exception from your console:

Processing:  38%|▍| 383/1000 [00:38<01:02,  9.84frame/s, memory_usage=05.60GB, execution_providers=['CUDAExecutionProvi
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\DEV\roop\roop\ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\DEV\roop\roop\ui.py", line 199, in select_output_path
    start()
  File "D:\DEV\roop\roop\core.py", line 168, in start
    frame_processor.process_video(roop.globals.source_path, temp_frame_paths)
  File "D:\DEV\roop\roop\processors\frame\face_enhancer.py", line 96, in process_video
    roop.processors.frame.core.process_video(None, temp_frame_paths, process_frames)
  File "D:\DEV\roop\roop\processors\frame\core.py", line 79, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, lambda: update_progress(progress))
  File "D:\DEV\roop\roop\processors\frame\core.py", line 57, in multi_process_frame
    future.result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\DEV\roop\roop\processors\frame\face_enhancer.py", line 83, in process_frames
    result = process_frame(None, None, temp_frame)
  File "D:\DEV\roop\roop\processors\frame\face_enhancer.py", line 76, in process_frame
    temp_frame = enhance_face(target_face, temp_frame)
  File "D:\DEV\roop\roop\processors\frame\face_enhancer.py", line 64, in enhance_face
    _, _, temp_face = get_face_enhancer().enhance(
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\gfpgan\utils.py", line 109, in enhance
    self.face_helper.read_image(img)
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\facexlib\utils\face_restoration_helper.py", line 114, in read_image
    if np.max(img) > 256:  # 16-bit image
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Users\Törk\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

## Details

What operating system are you using?

- [x] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [ ] 1.1.0
- [x] 1.2.0
- [ ] next

**Comment by henryruhs** [comment]
Please update to latest main branch - it has been fixed via https://github.com/s0md3v/roop/commit/75c8f583550bb66d01217f803635f8063781d6e1
