### ISSUE TITLE
roop not working

### ISSUE THREAD

**Issue by JO-R-D-AN** [s0md3v/roop#758]
followed the instructions for the cpu part to a T but it doesnt work
C:\Users\username\Desktop\New folder\roop>python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from roop import core
  File "C:\Users\username\Desktop\New folder\roop\roop\core.py", line 33
    def parse_args() -> None:
                     ^
SyntaxError: invalid syntax
i'm on windows 10

**Comment by henryruhs** [comment]
That is not a bug...
