### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by XTRMsavage** [s0md3v/roop#785]
when I run the command "python run.py",  I get this error

 "D:\roop\roop v1.3.1\roop>python run.py
Traceback (most recent call last):
  File "D:\roop\roop v1.3.1\roop\run.py", line 3, in <module>
    from roop import core
  File "D:\roop\roop v1.3.1\roop\roop\core.py", line 24, in <module>
    import roop.ui as ui
  File "D:\roop\roop v1.3.1\roop\roop\ui.py", line 7, in <module>
    import cv2
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found."

when I check for CV2 I get this error ">>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.
>>>

I have now installed and uninstalled openCV many times and I have put this "C:\opencv\build\x64\vc16\bin" in the edit environment variable path. But still not working, Can someone please help me to resolve this. Thank You

What operating system are you using?

- [x] Windows 
- [ ] MacOS (Apple Silicon)
- [ ] MacOS (Apple Legacy)
- [ ] Linux
- [ ] Linux in WSL

What execution provider are you using?

- [ ] CPU
- [x] CUDA
- [ ] CoreML
- [ ] DirectML
- [ ] OpenVINO
- [ ] Other

What version of Roop are you using?

- [ ] 1.0.0
- [x] 1.1.0
- [ ] 1.2.0
- [ ] 1.3.0
- [x] 1.3.1
- [ ] next

**Comment by henryruhs** [comment]
https://github.com/s0md3v/roop/wiki/4.-Troubleshooting#solution-to-most-opencv-errors
