### ISSUE TITLE
[Installation]An error occurred while installing and running on Mac mini M2.

### ISSUE THREAD

**Issue by shifangmingliangjun** [s0md3v/roop#796]
(c_f) walter@walterdeMini roop % python run.py
Traceback (most recent call last):
  File "/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/TkinterDnD.py", line 53, in _require
    TkdndVersion = tkroot.tk.call('package', 'require', 'tkdnd')
_tkinter.TclError: dlopen(/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib, 0x0006): tried: '/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (no such file), '/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/T7/change_face/roop/run.py", line 6, in <module>
    core.run()
  File "/Volumes/T7/change_face/roop/roop/core.py", line 223, in run
    window = ui.init(start, destroy)
  File "/Volumes/T7/change_face/roop/roop/ui.py", line 48, in init
    ROOT = create_root(start, destroy)
  File "/Volumes/T7/change_face/roop/roop/ui.py", line 61, in create_root
    root = CTk()
  File "/Volumes/T7/change_face/roop/roop/ui.py", line 42, in __init__
    self.TkdndVersion = TkinterDnD._require(self)
  File "/Volumes/T7/anaconda/anaconda3/envs/c_f/lib/python3.10/site-packages/tkinterdnd2/TkinterDnD.py", line 55, in _require
    raise RuntimeError('Unable to load tkdnd library.')
RuntimeError: Unable to load tkdnd library.

**Comment by aboutmydreams** [comment]
same problem in m1
```
export TK_SILENCE_DEPRECATION=1 
(.venv) ➜  roop git:(main) ✗ python3.9 ./run.py           
Traceback (most recent call last):
  File "/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/TkinterDnD.py", line 53, in _require
    TkdndVersion = tkroot.tk.call('package', 'require', 'tkdnd')
_tkinter.TclError: dlopen(/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib, 0x000A): tried: '/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (no such file), '/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/diven/coding/learn/roop/./run.py", line 6, in <module>
    core.run()
  File "/Users/diven/coding/learn/roop/roop/core.py", line 223, in run
    window = ui.init(start, destroy)
  File "/Users/diven/coding/learn/roop/roop/ui.py", line 48, in init
    ROOT = create_root(start, destroy)
  File "/Users/diven/coding/learn/roop/roop/ui.py", line 61, in create_root
    root = CTk()
  File "/Users/diven/coding/learn/roop/roop/ui.py", line 42, in __init__
    self.TkdndVersion = TkinterDnD._require(self)
  File "/Users/diven/coding/learn/roop/.venv/lib/python3.9/site-packages/tkinterdnd2/TkinterDnD.py", line 55, in _require
    raise RuntimeError('Unable to load tkdnd library.')
RuntimeError: Unable to load tkdnd library.
```
