### ISSUE TITLE
after run.py here errors

### ISSUE THREAD

**Issue by rexzhang2023** [s0md3v/roop#8]
(roop) rex@alienware17B:~/roop/roop$ python run.py --gpu
Traceback (most recent call last):
  File "/home/rex/roop/roop/run.py", line 8, in <module>
    from core.processor import process_video, process_img
  File "/home/rex/roop/roop/core/processor.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
(roop) rex@alienware17B:~/roop/roop$

**Comment by s0md3v** [comment]
install `python-opencv`.
