### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by heiheiheibj** [s0md3v/roop#812]
## Description

(roop) D:\roop>python run.py
[ WARN:0@608.158] global loadsave.cpp:248 cv::findDecoder imread_('G:/My Documents/amy鏂囨。/娌搏璇佷欢鐓ц摑搴?download_path: C:\Users\Administrator/.insightface\models\buffalo_l
Downloading C:\Users\Administrator/.insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|███████████████████████████████████████████████████████████████████████| 281857/281857 [00:20<00:00, 13850.52KB/s]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Administrator/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\roop\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\roop\roop\ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "D:\roop\roop\ui.py", line 199, in select_output_path
    start()
  File "D:\roop\roop\core.py", line 133, in start
    if not frame_processor.pre_start():
  File "D:\roop\roop\processors\frame\face_swapper.py", line 45, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
  File "D:\roop\roop\face_analyser.py", line 30, in get_one_face
    many_faces = get_many_faces(frame)
  File "D:\roop\roop\face_analyser.py", line 41, in get_many_faces
    return get_face_analyser().get(frame)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

```

```

## Details

What operating system are you using?
-Windows 10

What execution provider are you using?
- CPU

What version of Roop are you using?

- [ ] 1.3.2

thanks

**Comment by heiheiheibj** [comment]
The problem is solved. There are special characters in my file path, just change the path.
:P
