### ISSUE TITLE
I'm facing this problem with every mp4 file. Please help.

### ISSUE THREAD

**Issue by John4uSon** [s0md3v/roop#823]
I'm facing this problem with every mp4 file. Please help.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\saksh\AppData\Roaming\Python\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\TCHT\roop\roop\ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "C:\TCHT\roop\roop\ui.py", line 199, in select_output_path
    start()
  File "C:\TCHT\roop\roop\core.py", line 152, in start
    if predict_video(roop.globals.target_path):
  File "C:\TCHT\roop\roop\predictor.py", line 42, in predict_video
    _, probabilities = opennsfw2.predict_video_frames(video_path=target_path, frame_interval=100)
  File "C:\Users\saksh\AppData\Roaming\Python\Python310\site-packages\opennsfw2\_inference.py", line 184, in predict_video_frames
    cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

can u please help me??

**Comment by henryruhs** [comment]
Read the docs
