### ISSUE TITLE
I have this issue.. can not run roop

### ISSUE THREAD

**Issue by chemistiano** [s0md3v/roop#830]
(venv) E:\Deepface\roop>python run.py --keep-frames --keep-fps --core 1
Traceback (most recent call last):
  File "E:\Deepface\roop\run.py", line 3, in <module>
    from roop import core
  File "E:\Deepface\roop\roop\core.py", line 20, in <module>
    import roop.ui as ui
  File "E:\Deepface\roop\roop\ui.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by henryruhs** [comment]
We have this covered by our docs: https://roop-ai.gitbook.io/roop/troubleshooting#solution-to-most-opencv-errors
