### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by kotaxyz** [s0md3v/roop#849]
## Description

face swapper is working fine but everytime i do face enhancer i get this error
## Error

```


[ROOP.FACE-ENHANCER] Progressing...
Processing:   0%|                                                                           | 0/502 [00:07<?, ?frame/s]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Genesis\github\roop\roop\roop\ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
  File "C:\Users\Genesis\github\roop\roop\roop\ui.py", line 199, in select_output_path
    start()
  File "C:\Users\Genesis\github\roop\roop\roop\core.py", line 169, in start
    frame_processor.process_video(roop.globals.source_path, temp_frame_paths)
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\face_enhancer.py", line 104, in process_video
    roop.processors.frame.core.process_video(None, temp_frame_paths, process_frames)
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\core.py", line 79, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, lambda: update_progress(progress))
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\core.py", line 57, in multi_process_frame
    future.result()
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\face_enhancer.py", line 91, in process_frames
    result = process_frame(None, None, temp_frame)
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\face_enhancer.py", line 84, in process_frame
    temp_frame = enhance_face(target_face, temp_frame)
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\face_enhancer.py", line 72, in enhance_face
    _, _, temp_face = get_face_enhancer().enhance(
  File "C:\Users\Genesis\github\roop\roop\roop\processors\frame\face_enhancer.py", line 26, in get_face_enhancer
    FACE_ENHANCER = GFPGANer(model_path=model_path, upscale=1, device=get_device())
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\site-packages\gfpgan\utils.py", line 79, in __init__
    self.face_helper = FaceRestoreHelper(
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\site-packages\facexlib\detection\__init__.py", line 10, in init_detection_model
    model = RetinaFace(network_name='resnet50', half=half, device=device)
  File "C:\Users\Genesis\anaconda3\envs\roop\lib\site-packages\facexlib\detection\retinaface.py", line 86, in __init__
    self.mean_tensor = torch.tensor([[[[104.]], [[117.]], [[123.]]]], device=self.device)
  File "C:\Users\Genesis\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

## Details

What operating system are you using?

- [x] Windows 

What execution provider are you using?

- [x] CUDA

What version of Roop are you using?

- [x] 1.3.2

**Comment by henryruhs** [comment]
I think you did not use `pip install -r requirements.txt` and therefore installed `torch` instead of `torch==2.00.0+cu118`.

Join Discord for upcoming installation issues, GitHub is not the right place for that.
