### ISSUE TITLE
 'NoneType' object has no attribute 'configure'

### ISSUE THREAD

**Issue by ZhuJD-China** [s0md3v/roop#853]
PS D:\AIGC\roop> python .\run.py
E:\Anaconda\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
[ROOP.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "D:\AIGC\roop\run.py", line 6, in <module>
    core.run()
  File "D:\AIGC\roop\roop\core.py", line 210, in run
    if not pre_check():
           ^^^^^^^^^^^
  File "D:\AIGC\roop\roop\core.py", line 120, in pre_check
    update_status('ffmpeg is not installed.')
  File "D:\AIGC\roop\roop\core.py", line 128, in update_status
    ui.update_status(message)
  File "D:\AIGC\roop\roop\ui.py", line 143, in update_status
    status_label.configure(text=text)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'

**Comment by ZhuJD-China** [comment]
> Discord 不和谐

how to solve?
