### ISSUE TITLE
tried on kali linux stuck with AttributeError after install requirements

### ISSUE THREAD

**Issue by crossdefalt** [s0md3v/roop#854]
┌──(s1yn㉿sec)-[~/roop]
└─$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring tkinterdnd2-universal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring onnxruntime: markers 'python_version != "3.9" and sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-coreml: markers 'python_version == "3.9" and sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: numpy==1.24.3 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: opencv-python==4.8.0.74 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (4.8.0.74)
Requirement already satisfied: onnx==1.14.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: insightface==0.7.3 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.7.3)
Requirement already satisfied: psutil==5.9.5 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (5.9.5)
Requirement already satisfied: tk==0.1.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (0.1.0)
Requirement already satisfied: customtkinter==5.2.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (5.2.0)
Requirement already satisfied: tkinterdnd2==0.3.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (0.3.0)
Requirement already satisfied: pillow==10.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (10.0.0)
Requirement already satisfied: onnxruntime-gpu==1.15.1 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (1.15.1)
Requirement already satisfied: tensorflow==2.13.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: opennsfw2==0.10.2 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (0.10.2)
Requirement already satisfied: protobuf==4.23.4 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (4.23.4)
Requirement already satisfied: tqdm==4.65.0 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (4.65.0)
Requirement already satisfied: gfpgan==1.3.8 in /home/s1yn/.local/lib/python3.11/site-packages (from -r requirements.txt (line 21)) (1.3.8)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/s1yn/.local/lib/python3.11/site-packages (from onnx==1.14.0->-r requirements.txt (line 5)) (4.5.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (2.31.0)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (3.6.3)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (1.10.1)
Requirement already satisfied: scikit-learn in /home/s1yn/.local/lib/python3.11/site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: scikit-image in /home/s1yn/.local/lib/python3.11/site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (0.21.0)
Requirement already satisfied: easydict in /home/s1yn/.local/lib/python3.11/site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (1.10)
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (0.29.36)
Requirement already satisfied: albumentations in /home/s1yn/.local/lib/python3.11/site-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: prettytable in /usr/lib/python3/dist-packages (from insightface==0.7.3->-r requirements.txt (line 6)) (3.6.0)
Requirement already satisfied: darkdetect in /home/s1yn/.local/lib/python3.11/site-packages (from customtkinter==5.2.0->-r requirements.txt (line 9)) (0.8.0)
Requirement already satisfied: coloredlogs in /home/s1yn/.local/lib/python3.11/site-packages (from onnxruntime-gpu==1.15.1->-r requirements.txt (line 16)) (15.0.1)
Requirement already satisfied: flatbuffers in /home/s1yn/.local/lib/python3.11/site-packages (from onnxruntime-gpu==1.15.1->-r requirements.txt (line 16)) (23.5.26)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from onnxruntime-gpu==1.15.1->-r requirements.txt (line 16)) (23.1)
Requirement already satisfied: sympy in /usr/lib/python3/dist-packages (from onnxruntime-gpu==1.15.1->-r requirements.txt (line 16)) (1.12)
Requirement already satisfied: absl-py>=1.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.6.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.57.0)
Requirement already satisfied: h5py>=2.9.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (3.9.0)
Requirement already satisfied: keras<2.14,>=2.13.1 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.1)
Requirement already satisfied: libclang>=13.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (16.0.6)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (3.3.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (67.8.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: tensorboard<2.14,>=2.13 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (2.13.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/lib/python3/dist-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorflow==2.13.0->-r requirements.txt (line 17)) (0.33.0)
Requirement already satisfied: gdown>=4.2.0 in /home/s1yn/.local/lib/python3.11/site-packages (from opennsfw2==0.10.2->-r requirements.txt (line 18)) (4.7.1)
Requirement already satisfied: basicsr>=1.4.2 in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (1.4.2)
Requirement already satisfied: facexlib>=0.2.5 in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (0.3.0)
Requirement already satisfied: lmdb in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (1.4.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (6.0.1)
Requirement already satisfied: tb-nightly in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (2.15.0a20230816)
Requirement already satisfied: torch>=1.7 in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (2.0.1+cu118)
Requirement already satisfied: torchvision in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (0.15.2+cu118)
Requirement already satisfied: yapf in /home/s1yn/.local/lib/python3.11/site-packages (from gfpgan==1.3.8->-r requirements.txt (line 21)) (0.40.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.38.4)
Requirement already satisfied: addict in /home/s1yn/.local/lib/python3.11/site-packages (from basicsr>=1.4.2->gfpgan==1.3.8->-r requirements.txt (line 21)) (2.4.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from basicsr>=1.4.2->gfpgan==1.3.8->-r requirements.txt (line 21)) (0.18.2)
Requirement already satisfied: filterpy in /home/s1yn/.local/lib/python3.11/site-packages (from facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 21)) (1.4.5)
Requirement already satisfied: numba in /usr/lib/python3/dist-packages (from facexlib>=0.2.5->gfpgan==1.3.8->-r requirements.txt (line 21)) (0.56.4)
Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 18)) (3.12.2)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 18)) (4.12.2)
Requirement already satisfied: networkx>=2.8 in /usr/lib/python3/dist-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 6)) (2.8.8)
Requirement already satisfied: imageio>=2.27 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 6)) (2.31.1)
Requirement already satisfied: tifffile>=2022.8.12 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 6)) (2023.8.12)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 6)) (1.4.1)
Requirement already satisfied: lazy_loader>=0.2 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 6)) (0.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.22.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3/dist-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (3.4.4)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/s1yn/.local/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/lib/python3/dist-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (2.2.2)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from torch>=1.7->gfpgan==1.3.8->-r requirements.txt (line 21)) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from torch>=1.7->gfpgan==1.3.8->-r requirements.txt (line 21)) (2.0.0)
Requirement already satisfied: cmake in /home/s1yn/.local/lib/python3.11/site-packages (from triton==2.0.0->torch>=1.7->gfpgan==1.3.8->-r requirements.txt (line 21)) (3.27.2)
Requirement already satisfied: lit in /home/s1yn/.local/lib/python3.11/site-packages (from triton==2.0.0->torch>=1.7->gfpgan==1.3.8->-r requirements.txt (line 21)) (16.0.6)
Requirement already satisfied: qudida>=0.0.4 in /home/s1yn/.local/lib/python3.11/site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 6)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /home/s1yn/.local/lib/python3.11/site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 6)) (4.8.0.76)
Requirement already satisfied: humanfriendly>=9.1 in /home/s1yn/.local/lib/python3.11/site-packages (from coloredlogs->onnxruntime-gpu==1.15.1->-r requirements.txt (line 16)) (10.0)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prettytable->insightface==0.7.3->-r requirements.txt (line 6)) (0.2.5)
Requirement already satisfied: joblib>=1.1.1 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 6)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: importlib-metadata>=6.6.0 in /home/s1yn/.local/lib/python3.11/site-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 21)) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in /usr/lib/python3/dist-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 21)) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in /usr/lib/python3/dist-packages (from yapf->gfpgan==1.3.8->-r requirements.txt (line 21)) (2.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (4.8)
Requirement already satisfied: urllib3<2.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.26.16)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/s1yn/.local/lib/python3.11/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (1.3.1)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=6.6.0->yapf->gfpgan==1.3.8->-r requirements.txt (line 21)) (1.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->gdown>=4.2.0->opennsfw2==0.10.2->-r requirements.txt (line 18)) (2.4.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3/dist-packages (from requests->insightface==0.7.3->-r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in /home/s1yn/.local/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r requirements.txt (line 17)) (3.2.2)
Requirement already satisfied: more-itertools in /usr/lib/python3/dist-packages (from zipp>=0.5->importlib-metadata>=6.6.0->yapf->gfpgan==1.3.8->-r requirements.txt (line 21)) (10.1.0)
                                                                                 
┌──(s1yn㉿sec)-[~/roop]
└─$ python run.py                  
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/s1yn/.local/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/s1yn/roop/roop/ui.py", line 81, in <lambda>
    source_button = ctk.CTkButton(root, text='Select a face', cursor='hand2', command=lambda: select_source_path())
                                                                                              ^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/ui.py", line 157, in select_source_path
    image = render_image_preview(roop.globals.source_path, (200, 200))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/ui.py", line 203, in render_image_preview
    image = Image.open(image_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/s1yn/roop/samp.HEIC'
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/s1yn/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/s1yn/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/s1yn/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/s1yn/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/s1yn/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/s1yn/.local/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/s1yn/roop/roop/ui.py", line 103, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', cursor='hand2', command=lambda: select_output_path(start))
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/ui.py", line 199, in select_output_path
    start()
  File "/home/s1yn/roop/roop/core.py", line 133, in start
    if not frame_processor.pre_start():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/processors/frame/face_swapper.py", line 45, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/face_analyser.py", line 30, in get_one_face
    many_faces = get_many_faces(frame)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/roop/roop/face_analyser.py", line 41, in get_many_faces
    return get_face_analyser().get(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/.local/lib/python3.11/site-packages/insightface/app/face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1yn/.local/lib/python3.11/site-packages/insightface/model_zoo/retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
                     ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by henryruhs** [comment]
Install issues are closed - join Discord for help
