### ISSUE TITLE
after run.py pass cv2 and other error

### ISSUE THREAD

**Issue by rexzhang2023** [s0md3v/roop#9]
(roop) rex@alienware17B:~/roop/roop$ python run.py --gpu
Traceback (most recent call last):
  File "/home/rex/roop/roop/run.py", line 9, in <module>
    from core.processor import process_video, process_img
  File "/home/rex/roop/roop/core/processor.py", line 2, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by rexzhang2023** [comment]
(roop) rex@alienware17B:~/roop/roop$ python run.py --gpu
Traceback (most recent call last):
  File "/home/rex/miniconda3/envs/roop/lib/python3.11/site-packages/insightface/__init__.py", line 8, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rex/roop/roop/run.py", line 9, in <module>
    from core.processor import process_video, process_img
  File "/home/rex/roop/roop/core/processor.py", line 2, in <module>
    import insightface
  File "/home/rex/miniconda3/envs/roop/lib/python3.11/site-packages/insightface/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime.

**Comment by s0md3v** [comment]
read docs, use google.

**Comment by rexzhang2023** [comment]
after install onnxruntime , it is working...download models..thanks

**Comment by gnjnshh** [comment]
Traceback (most recent call last):
  File "D:\Code\roop\run.py", line 22, in <module>
    from core.processor import process_video, process_img
  File "D:\Code\roop\core\processor.py", line 3, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'
 same error, how did you solve it? thanks
